version: '3'
services:
    tigergraph:
        container_name: tigergraph-yelp
        image: "docker.tigergraph.com/tigergraph-dev:latest"
        ports:
            - "14022:22"
            - "9000:9000"
            - "14240:14240"
        volumes:
            - tigergraph-yelp:/var/lib/tigergraph/data
        ulimits:
            nofile:
                soft: 1000000
                hard: 1000000
        stdin_open: true
        tty: true
volumes:
    tigergraph-yelp:
